seed: 829304518
weights_path: "weights/aggregation_network.pt"
diffusion_mode: "generation"
output_resolution: 64
batch_size: 2
prompt: ""
# From https://twitter.com/EMostaque/status/1596905782859436033
negative_prompt: "poorly drawn, ugly, tiling, out of frame, mutation, mutated, extra limbs, extra legs, extra arms, disfigured, deformed, cross-eye, body out of frame, blurry, bad art, bad anatomy, blurred, text, watermark, grainy,  writing, calligraphy, sign, cut off"
guidance_scale: 7.5
flip_timesteps: True